---
- hosts: all

  become: yes
  become_user: root

  tasks:

    - name: Install php repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Remove existing php packages
      apt:
        name: php*
        state: absent
        purge: true

    - name: Install apt packages
      apt:
        name: '{{ item }}'
        update_cache: yes
        state: latest
      with_items:
        - nodejs
        - npm
        - apache2
        - libapache2-mod-php5.6
        - php5.6-common
        - php5.6-cli
        - php5.6-curl
        - php5.6-json
        - php5.6-mysql
        - mysql-server
        - python2.7-mysqldb

    - name: Symlink Node binary
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        owner: root
        group: root
        state: link

    - name: Install global Bower package
      npm:
        name: bower
        state: present
        global: yes

    - name: Clone jbull.ca
      git:
        clone: yes
        repo: https://github.com/jabes/website-2012
        dest: /var/www/jbull.ca

    - name: Clone pinup.jbull.ca
      git:
        clone: yes
        repo: https://github.com/jabes/pinup
        dest: /var/www/pinup.jbull.ca

    - name: Clone reports.jbull.ca
      git:
        clone: yes
        repo: https://github.com/jabes/pinup-reports
        dest: /var/www/reports.jbull.ca

    - name: Remove all apache sites
      file:
        state: absent
        path: '{{ item }}'
      with_items:
        - /etc/apache2/sites-available/*
        - /etc/apache2/sites-enabled/*

    - name: Add jbull.ca vhosts configuration
      template:
        src: vhosts.conf.j2
        dest: /etc/apache2/sites-available/jbull.ca.conf
        owner: root
        group: root
        mode: 0644
      vars:
        server_name: jbull.ca
        server_alias: www.jbull.ca
        document_root: /var/www/jbull.ca

    - name: Add pinup.jbull.ca vhosts configuration
      template:
        src: vhosts.conf.j2
        dest: /etc/apache2/sites-available/pinup.jbull.ca.conf
        owner: root
        group: root
        mode: 0644
      vars:
        server_name: pinup.jbull.ca
        document_root: /var/www/pinup.jbull.ca

    - name: Add reports.jbull.ca vhosts configuration
      template:
        src: vhosts.conf.j2
        dest: /etc/apache2/sites-available/reports.jbull.ca.conf
        owner: root
        group: root
        mode: 0644
      vars:
        server_name: reports.jbull.ca
        document_root: /var/www/reports.jbull.ca

    - name: Enable jbull.ca vhost
      command: a2ensite jbull.ca.conf
      notify: restart apache

    - name: Enable pinup.jbull.ca vhost
      command: a2ensite pinup.jbull.ca.conf
      notify: restart apache

    - name: Enable reports.jbull.ca vhost
      command: a2ensite reports.jbull.ca.conf
      notify: restart apache

    - name: Set permissions for root mysql user
      mysql_user:
        name: root
        password: root
        priv: '*.*:ALL'
        state: present

    - name: Replace localhost domains with production domains for pinup
      replace:
        path: '{{ item }}'
        regexp: '(\s+)pinup\.dev(\s+.*)?$'
        replace: '\1pinup.jbull.ca\2'
        backup: yes
      with_items:
        - /var/www/pinup.jbull.ca/build/js/prefs.js
        - /var/www/pinup.jbull.ca/cdn/frontend-js/pinup.js
        - /var/www/pinup.jbull.ca/cdn/frontend-js/pinup.min.js
        - /var/www/pinup.jbull.ca/gateway/php/config.php
        - /var/www/pinup.jbull.ca/sql/seed.sql

    - name: Create pinup database
      mysql_db:
        name: pinup
        state: present

    - name: Import pinup .sql files
      mysql_db:
        name: pinup
        state: import
        target: '/var/www/pinup.jbull.ca/sql/{{ item }}.sql'
      with_items:
        - schema
        - seed

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
