---
- hosts: all

  become: yes
  become_user: root

  tasks:

    - name: Install php repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Remove existing php packages
      apt:
        name: php*
        state: absent
        purge: true

    - name: Install packages
      apt:
        name: '{{ item }}'
        update_cache: yes
        state: latest
      with_items:
        - nodejs
        - npm
        - apache2
        - libapache2-mod-php5.6
        - php5.6-common
        - php5.6-cli
        - php5.6-curl
        - php5.6-json
        - php5.6-mysql
        - mysql-server
        - python2.7-mysqldb

    - name: Clone jbull.ca
      git:
        clone: yes
        repo: https://github.com/jabes/website-2012
        dest: /var/www/jbull.ca

    - name: Clone pinup.jbull.ca
      git:
        clone: yes
        repo: https://github.com/jabes/pinup
        dest: /var/www/pinup.jbull.ca

    - name: Clone knackcommerce.com
      git:
        clone: yes
        repo: https://github.com/jabes/knack-commerce
        dest: /var/www/knackcommerce.com

    - name: Add jbull.ca vhosts configuration
      template:
        src: vhosts.conf.j2
        dest: /etc/apache2/sites-available/jbull.ca.conf
        owner: root
        group: root
        mode: 0644
      vars:
        server_name: jbull.ca
        server_alias: www.jbull.ca
        document_root: /var/www/jbull.ca

    - name: Add pinup.jbull.ca vhosts configuration
      template:
        src: vhosts.conf.j2
        dest: /etc/apache2/sites-available/pinup.jbull.ca.conf
        owner: root
        group: root
        mode: 0644
      vars:
        server_name: pinup.jbull.ca
        document_root: /var/www/pinup.jbull.ca

    - name: Add knackcommerce.com vhosts configuration
      template:
        src: vhosts.conf.j2
        dest: /etc/apache2/sites-available/knackcommerce.com.conf
        owner: root
        group: root
        mode: 0644
      vars:
        server_name: knackcommerce.com
        server_alias: www.knackcommerce.com
        document_root: /var/www/knackcommerce.com

    - name: Disable default vhost
      command: a2dissite 000-default.conf
      notify: restart apache

    - name: Enable jbull.ca vhost
      command: a2ensite jbull.ca.conf
      notify: restart apache

    - name: Enable pinup.jbull.ca vhost
      command: a2ensite pinup.jbull.ca.conf
      notify: restart apache

    - name: Enable knackcommerce.com vhost
      command: a2ensite knackcommerce.com.conf
      notify: restart apache

    - name: Create pinup database
      mysql_db:
        name: pinup
        state: present

    - name: Import pinup .sql files
      mysql_db:
        name: pinup
        state: import
        target: '/var/www/pinup.jbull.ca/sql/{{ item }}.sql'
      with_items:
        - schema
        - seed

    - name: Symlink Node binary
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        owner: root
        group: root
        state: link

    - name: Install Bower
      npm:
        name: bower
        state: present
        global: yes

    - name: Install knackcommerce.com bower packages
      command: bower install --allow-root
      args:
        chdir: /var/www/knackcommerce.com

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
