---
- hosts: all

  become: yes
  become_user: root

  tasks:

    - name: Purge existing packages that will soon be replaced
      apt:
        name: '{{ item }}'
        state: absent
        purge: true
      with_items:
        - php*
        - mysql*

    - name: Set mysql debconf
      debconf:
        name: '{{ item.name }}'
        question: '{{ item.question }}'
        value: '{{ item.value }}'
        vtype: '{{ item.type }}'
      with_items:
        - { name: mysql-server, question: mysql-server/root_password, type: password, value: root }
        - { name: mysql-server, question: mysql-server/root_password_again, type: password, value: root }

    - name: Install apt packages
      apt:
        name: '{{ item }}'
        update_cache: yes
        state: latest
      with_items:
        - apache2
        - libapache2-mod-php5
        - php5-common
        - php5-curl
        - php5-json
        - php5-mcrypt
        - php5-memcache
        - php5-mysql
        - mysql-server
        - python-mysqldb # used by ansible mysql_db module

    - name: Enable php modules
      shell: 'php5enmod {{ item }}'
      with_items:
        - mcrypt
        - memcache

    - name: Enable apache modules
      apache2_module:
        name: '{{ item }}'
        state: present
      with_items:
        - rewrite
      notify: restart apache

    - name: Clone website repositories into their docroot folders
      git:
        repo: '{{ item.repo }}'
        dest: '{{ item.dest }}'
        clone: yes
        force: yes
      with_items:
        - { repo: 'https://github.com/jabes/website-2012', dest: /var/www/jbull.ca }
        - { repo: 'https://github.com/jabes/pinup', dest: /var/www/pinup.jbull.ca }
        - { repo: 'https://github.com/jabes/pinup-reports', dest: /var/www/reports.jbull.ca }

    - name: Replace pinup localhost domains with production domains
      replace:
        dest: '{{ item }}'
        regexp: '^(.*)?pinup\.dev(.*)?$'
        replace: '\1pinup.jbull.ca\2'
      with_items:
        - /var/www/pinup.jbull.ca/build/js/prefs.js
        - /var/www/pinup.jbull.ca/cdn/frontend-js/pinup.js
        - /var/www/pinup.jbull.ca/cdn/frontend-js/pinup.min.js
        - /var/www/pinup.jbull.ca/sql/seed.sql

    - name: Add vhost configurations
      template:
        src: vhosts.conf.j2
        dest: '/etc/apache2/sites-available/{{ item.name }}.conf'
        owner: root
        group: root
        mode: 0644
      vars:
        server_name: '{{ item.name }}'
        server_alias: '{{ item.alias | default(false) }}'
        document_root: '/var/www/{{ item.name }}'
      with_items:
        - { name: jbull.ca, alias: www.jbull.ca }
        - { name: pinup.jbull.ca }
        - { name: reports.jbull.ca }

    - name: Disable default vhost
      command: 'a2dissite {{ item }}.conf'
      notify: restart apache
      with_items:
        - 000-default

    - name: Enable vhosts
      command: 'a2ensite {{ item }}.conf'
      notify: restart apache
      with_items:
        - jbull.ca
        - pinup.jbull.ca
        - reports.jbull.ca

    - name: Update MySQL root password for all root accounts
      mysql_user:
        host: '{{ item }}'
        name: root
        password: root
        login_user: root
        login_password: root
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
        state: present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Create pinup database
      mysql_db:
        name: pinup
        login_user: root
        login_password: root
        state: present

    - name: Import pinup .sql files
      mysql_db:
        name: pinup
        login_user: root
        login_password: root
        state: import
        target: '/var/www/pinup.jbull.ca/sql/{{ item }}.sql'
      with_items:
        - schema
        - seed

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
