- name: Clone jbull.ca
  git:
    clone: yes
    repo: https://github.com/jabes/website-2012
    dest: /var/www/jbull.ca

- name: Clone pinup.jbull.ca
  git:
    clone: yes
    repo: https://github.com/jabes/pinup
    dest: /var/www/pinup.jbull.ca

- name: Clone knackcommerce.com
  git:
    clone: yes
    repo: https://github.com/jabes/knack-commerce
    dest: /var/www/knackcommerce.com

- name: Import pinup .sql files
  mysql_db:
    state: import
    name: pinup
    target: /var/www/pinup.jbull.ca/sql/{{ item.name }}.sql
  with_items:
    - schema
    - seed
